[build]
command = "cd docs && pnpm install --frozen-lockfile && pnpm run docs:build"
publish = "docs/.vitepress/dist"

[build.environment]
NODE_VERSION = "18"
PNPM_VERSION = "8"
NPM_FLAGS = "--production=false"

[[redirects]]
from = "/quick-start"
to = "/essentials/getting-started"
status = 301

[[redirects]]
from = "/api-reference"
to = "/api/core-functions"
status = 301

[[redirects]]
from = "/why-this-library"
to = "/introduction/what-is-i18n-at"
status = 301

[[redirects]]
from = "/advanced-usage"
to = "/advanced/typescript-support"
status = 301
